TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += keithley_2001.db
DATA += keithley_2001.proto

#=======================================
include $(TOP)/configure/RULES
