TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Add dbd files
DBD += keithley_2001_buffer_parsing.dbd
DBD += keithley_2001_state_machine.dbd

#----------------------------------------------------

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

