TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Add dbd files
DBD += keithley_2001_sm.dbd
DBD += keithley_2001_asub.dbd

#----------------------------------------------------

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

