TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Add dbd file to register VISA register
DBD += keithley_2001_sm.dbd

#----------------------------------------------------

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

